config/routes.rb
Rails.application.routes.draw do
  get 'events/join'

  get 'events/index'

  root to: 'static_pages#home'
  get 'signup',  to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, except: [:index, :new]
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :events
  resources :relationships, only: [:create, :destroy]

  resources :users do #課題
    member do
      get :followings
      get :followers
    end
  end

  resources :events do
    member do
      get :attend
      get :unattend
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  validates :area, presence: true, length: { maximum: 40 }, on: :update
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :microposts
  has_many :attendees
  has_many :events, through: :attendees
  has_many :following_relationships, class_name:  "Relationship",
                                     foreign_key: "follower_id",
                                     dependent:   :destroy
  has_many :following_users, through: :following_relationships, source: :followed
  has_many :follower_relationships, class_name:  "Relationship",
                                     foreign_key: "followed_id",
                                     dependent:   :destroy
  has_many :follower_users, through: :follower_relationships, source: :follower
  

  # 他のユーザーをフォローする
  def follow(other_user)
    following_relationships.create(followed_id: other_user.id)
  end

  # フォローしているユーザーをアンフォローする
  def unfollow(other_user)
    following_relationships.find_by(followed_id: other_user.id).destroy
  end

  # あるユーザーをフォローしているかどうか？
  def following?(other_user)
    following_users.include?(other_user)
  end

  def feed_items
    Micropost.where(user_id: following_user_ids + [self.id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:edit, :update]
  
  def show
   @user = User.find(params[:id])
   @microposts = @user.microposts.page(params[:page]).per(5) #ページネーション
   @events = Event.new
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the skate player!" # アラート
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end
  
  def update
    if @user.update(user_params)
      # 保存に成功した場合はトップページへリダイレクト
      flash[:success] = "プロフィールを編集しました"
      redirect_to user_path
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end

  def followings #課題
    @user = User.find(params[:id])
    @users = @user.following_users.page(params[:page]).per(5) #ページネーション
  end

  def followers #課題
    @user = User.find(params[:id])
    @users = @user.follower_users.page(params[:page]).per(5) #ページネーション
  end

  def index
    @users = User.all.page(params[:page])
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :area, :email, :password,
                                 :password_confirmation)
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/
#{gravatar_id}
?s=
#{size}
"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/users/_follow.html.erb
<%= form_for(current_user.following_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% if current_user != @user %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.following_relationships.find_by(followed_id: @user.id),
             html: { method: :delete },
             remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/edit.html.erb
<h1>ユーザープロフィールの編集</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'  %>

      <%= f.label :area %>
      <%= f.text_field :area, class: 'form-control'  %>
      
      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control'  %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control'  %>

      <%= f.label :password_confirmation, "Confirm Password" %>
      <%= f.password_field :password_confirmation, class: 'form-control'  %>

      <%= f.submit "update", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/followers.html.erb
<h1>followers</h1>
<hr />
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <ul>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </ul>
    </section>
  </aside>
  <div class="col-md-8">
    <section class="user_info">
      <ul style="list-style-type: none"> <!--マークを消す-->
      <ul id="blank-list">  
        <% @users.each do |u| %>
          <li class="clearfix">
        <%= gravatar_for u %>
        <%= u.name %>
          </li>
        <% end %>
      </ul>
      </ul>
      <%= paginate @users, :params => {:controller => 'users', :action => 'followers'} %>
    </section>
  </div>
</div>

app/views/users/followings.html.erb
<h1>followings</h1>
<hr />
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <ul>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </ul>
    </section>
  </aside>
  <div class="col-md-8">
    <section class="user_info">
      <ul style="list-style-type: none"> <!--マークを消す-->
      <ul id="blank-list">  
        <% @users.each do |u| %>
          <li class="clearfix">
        <%= gravatar_for u %>
        <%= u.name %>
          </li>
        <% end %>
      </ul>
      </ul>
      <%= paginate @users, :params => {:controller => 'users', :action => 'followings'} %>
    </section>
  </div>
</div>

app/views/users/index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    ユーザー一覧
  </div>

  <div class="panel-body">
    <ul style="list-style-type: none">
    <ul id="blank-list">
    <% @users.each do |user| %>
      <li class="clearfix">
        <%= link_to gravatar_for(user, size: 50), user %>
        <span class="user"><%= link_to user.name, user %></span>
      </li>
    <% end %>
    </ul>
    <%= paginate @users %>
  </div>
</div>

app/views/users/new.html.erb
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control'  %>

      <%= f.label :email %>
      <%= f.text_field :email, class: 'form-control'  %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control'  %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user %>
        <%= @user.name %>
      </h1>
      <div><%= link_to "Followings", followings_user_path(@user) %></div> <!--課題-->
      <div><%= link_to "Followers", followers_user_path(@user) %></div>
    </section>
  </aside>
  <div class="col-md-8">
    <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= paginate @microposts, :params => {:controller => 'users', :action => 'show'} %>
    <% end %>
  </div>
</div>