config/routes.rb
Rails.application.routes.draw do
  get 'events/join'

  get 'events/index'

  root to: 'static_pages#home'
  get 'signup',  to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  
  resources :users, except: [:index, :new]
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts
  resources :events
  resources :relationships, only: [:create, :destroy]

  resources :users do #課題
    member do
      get :followings
      get :followers
    end
  end

  resources :events do
    member do
      get :attend
      get :unattend
    end
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
  has_many :attendees
  has_many :users, through: :attendees
  has_many :microposts
  
  # イベントに参加する
  def participant(current_user)
    attendees.find_or_create_by(user_id:current_user.id)
  end

  # 参加しているイベントから抜ける
  def nonparticipant(current_user)
    attendees.find_by(user_id:current_user.id).destroy
  end

  # あるイベントに参加しているかどうか？
  def participant?(current_event)
    attendee_events.include?(current_event)
  end

  def feed_items
    Micropost.where(user_id: attendee_user_ids + [current_user.id])
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:edit, :update, :destroy]
  
  def index
    @events = Event.all
  end
  
  def new
    if logged_in?
      @events = Event.new
    else
      flash[:warning] = "ログインしてください"
      redirect_to login_path
    end
  end
  
  def create
      @event = Event.new(event_params)
      @event.save
      flash[:success] = "イベントを保存しました"
      redirect_to events_path
  end
  
  def edit
    @event = Event.find(params[:id])
  end
  
  def show
    @event = Event.find(params[:id])
  end
  
  def join
    
  end
  
  def attend
    if logged_in?
    @event = Event.find(params[:id])
    @attendee = @event.attendees.create(user_id:current_user.id)
    @count = @event.attendees.size
    
    else
    redirect_to login_path
    end
  end
  
  def unattend
    @event = Event.find(params[:id])
    @count = @event.attendees.size
    @attendee = @event.attendees.find_by(user_id:current_user.id).destroy
  end
  
  def update
    if @event.update(event_params)
    flash[:success] = "イベントを保存しました"
    redirect_to events_path
    else
    render 'edit'
    end
  end
  
  def destroy
    @event.destroy
    flash[:warning] = "イベントを削除しました"
    redirect_to events_path
  end
  
  private
  def event_params
    params.require(:event).permit(:place, :time)
  end
  
  def set_event
    @event = Event.find(params[:id])
  end
end

app/views/events/_attend.js.erb
$("#event-attend").html("<%= escape_javascript(render('events/unattend')) %>");

app/views/events/_form.html.erb
<%= form_for(@event) do |e| %>
  <%# 入力コントロール %>
  場所:
  <%= e.text_field :place %>
  
  時間:
  <%= e.text_field :time %>
  <%= e.submit "Edit Event", class: "btn btn-large btn-primary" %>
<% end %>

app/views/events/_unattend.js.erb
$("#event-unattend").html("<%= escape_javascript(render('events/attend')) %>");

app/views/events/attend.html.erb
<div class="panel-heading">
<% if @event.attendees.any? %>  
  <%= @event.attendees.count %>
<% end %>
  <%= @event.place %>
</div>
  
<div class="panel-body">
  <span class="label label-info"><%= @event.time %></span>
</div>

<% if logged_in? %>
  <div id="event-attend" >
    <%= link_to "Unjoin", unattend_event_path(@event), class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/events/attend.js.erb
$("#event-attend").html("<%= escape_javascript(render('events/unattend')) %>");

app/views/events/edit.html.erb
<h1>内容の編集</h1>

<%= render 'form' %>

app/views/events/index.html.erb
    
<% @events.each_with_index do |event, i| %>

<% if i % 4 == 0 %>
<div class="row">
<% end %>
(<%= link_to "edit" , edit_event_path(event) %>
 <%= link_to "destroy" , event , method: :delete, data: { confirm: '削除してもよろしいですか？' } %>
 )
 <br />

<%= link_to event_path(event) do %>

  <div class="col-sm-3 panel panel-default">
    <div class="panel-heading">
      <%= event.place %>
      
    </div>
  
    <div class="panel-body">
        <span class="label label-info"><%= event.time %></span>
    </div>
  </div>

<% end %>
<% end %>
</div>

app/views/events/join.html.erb
<h1>Events#join</h1>
<p>Find me in app/views/events/join.html.erb</p>

app/views/events/new.html.erb
<%= form_for(Event.new) do |f| %>
  <%# 入力コントロール %>
  場所:
  <%= f.text_field :place %>
  
  時間:
  <%= f.text_field :time %>
  <%= f.submit "Create Event", class: "btn btn-large btn-primary" %>
<% end %>

app/views/events/show.html.erb
<div class="panel-heading">
<% if @event.attendees.any? %>  
  <%= @event.attendees.count %>
<% end %>
  <%= @event.place %>
</div>
  
<div class="panel-body">
  <span class="label label-info"><%= @event.time %></span>
</div>

<%= link_to "Join", attend_event_path(@event), class: "btn btn-lg btn-primary" %>

app/views/events/unattend.html.erb
<div class="panel-heading">
<% if @event.attendees.any? %>  
  <%= @event.attendees.count %>
<% end %>
  <%= @event.place %>
</div>
  
<div class="panel-body">
  <span class="label label-info"><%= @event.time %></span>
</div>

<% if logged_in? %>
  <div id="event-attend" >
    <%= link_to "join", attend_event_path(@event), class: "btn btn-lg btn-primary", remote: true%>
  </div>
<% end %>

app/views/events/unattend.js.erb
$("#event-unattend").html("<%= escape_javascript(render('events/attend')) %>");